version: '2'
services:
  api:
    build: ./api
    command: supervisord -n
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    links:
      - mongo:mongo
    environment:
      - MONGO_URI=mongodb://mongo/weather
      - PORT=8000
      - API_TOKEN=034c83c7d53baff2f137e5f3374aa126
      - DEBUG=true
#  ui:
#    build: ./ui
#    command: npm start
#    volumes:
#      - ./ui:/app
#    ports:
#      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
