version: '2'
services:
  api:
    build: ./api
    command: supervisord -n
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    links:
      - redis:redis
    environment:
      - REDIS_HOST=redis
#  ui:
#    build: ./ui
#    command: npm start
#    volumes:
#      - ./ui:/app
#    ports:
#      - "3000:3000"
  redis:
    image: redis
    environment:
      - DEBUG_MODE=True
